api_platform:
    eager_loading:
      max_joins: 100
    title: 'Climbing eshop'
    description: 'Symfony API to manage climbing eshop'
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
