vich_uploader:
  db_driver: orm

  mappings:
    media_object:
      uri_prefix: /assets/img
      upload_destination: '%kernel.project_dir%/public/assets/img'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

  #mappings:
  #    products:
  #        uri_prefix: /images/products
  #        upload_destination: '%kernel.project_dir%/pu