#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# config/routes.yaml
authentication_token:
  path: /api/login
  methods: [ 'POST' ]


#api_me:
#  path: /api/products/category
#  methods: [ 'GET' ]
#  defaults:
#    _controller: '\App\Controller\ProductController::findAllByCategory'
#    _api_resource_class: 'App\Entity\Product'
#    _api_collection_operation_name: 'collName_api_me'
